[package]
name = "nadeo-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.0"
reqwest = { version = "0.12.3", features = ["json"] }
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros"] }
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
thiserror = "1.0.58"
chrono = "0.4.38"
strum = { version = "0.26.2", features = ["strum_macros", "derive"] }
derive_more = "0.99.17"
futures = "0.3.30"
